// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pebydxekkvorlvjgompk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlYnlkeGVra3Zvcmx2amdvbXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzM4NzUsImV4cCI6MjA2NDcwOTg3NX0.ZCij5h09p_-6ABluz-zLnzUtWV_cfuDEoJU99YuCgOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);